on:
  push:
    branches: [main]
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest

      steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          run: go test ./... -cover

      - name: build
        run: ./scripts/build.sh
