name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          run: go test ./... -cover

      - name: Force Success
        run: (exit 0)
  Style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          run: test -z $(go fmt ./...)
          
      - name: Run staticcheck
        run: staticcheck ./...

      - name: Force Success
        run: (exit 0)